[package]
name = "deadlock-live-events"
version = "0.1.0"
edition = "2024"
description = "API for Deadlock live events"
repository = "https://github.com/deadlock-api/deadlock-live-events"
license = "MIT"

[dependencies]
reqwest = { version = "0.12.26", features = ["json", "http2", "gzip"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
axum = "0.8.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tower-layer = "0.3.3"
tower-http = { version = "0.6.6", features = ["cors", "normalize-path", "trace", "limit"] }
tracing = "0.1.41"
futures = "0.3.31"
valveprotos = { git = "https://github.com/deadlock-api/valveprotos-rs.git", rev = "08baa963331b196ca3271da3799aa1211dc1641c", features = ["serde", "user-msgs", "game-msgs"] }
prost = "0.14.1"
tryhard = "0.5.2"
strum = { version = "0.27.2", features = ["derive"] }
haste = { git = "https://github.com/deadlock-api/haste.git", rev = "d05a7b5a4f3bb61bc25f2de2564d2eb51ebcdeb8" }
async-stream = "0.3.6"
thiserror = "2.0.17"
serde-env = "0.2.0"
bytes = "1.11.0"
